import { beforeEach, it, expect } from 'vitest'
import { renderRoute } from '../../test/setup.tsx'
import App from '../App'
import * as api from '../api/bridge'
import { render } from 'react-dom'
import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import SingleBridge from './SingleBridge'
